config/routes.rb
Rails.application.routes.draw do

  resources :workout_classes
  root 'home#index'

  get '/calendar', to: 'calendar#index'
  get '/load', to: 'workout_transactions#load'
  post '/parse', to: 'workout_transactions#parse'
  
  resources :workout_transactions
  resources :cardio_definitions
  resources :mma_definitions
  resources :weightlifting_definitions
  resources :workout_definitions

end

app/models/calendar.rb
class Calendar < ActiveRecord::Base
end

app/models/cardio_definition.rb
class CardioDefinition < WorkoutDefinition
end

app/models/mma_definition.rb
class MmaDefinition < WorkoutDefinition
end

app/models/weightlifting_definition.rb
class WeightliftingDefinition < WorkoutDefinition
end

app/models/workout_class.rb
class WorkoutClass < ActiveRecord::Base
  belongs_to :workout_definition
end

app/models/workout_definition.rb
class WorkoutDefinition < ActiveRecord::Base
	has_many :workout_maps
	has_many :workout_transactions, through: :workout_maps
	attr_accessor :most_recent
end

app/models/workout_map.rb
class WorkoutMap < ActiveRecord::Base
	belongs_to :workout_transaction
	belongs_to :workout_definition
end

app/models/workout_transaction.rb
class WorkoutTransaction < ActiveRecord::Base
	has_many :workout_maps
	has_many :workout_definitions, through: :workout_maps
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/calendar_controller.rb
class CalendarController < ApplicationController
	def index
		@txns = WorkoutTransaction.all
		@classes = WorkoutClass.all
		
	end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
	def index
		@workout_defs = WorkoutDefinition.all.group_by{|d| d.type}
	end
end

app/controllers/mma_definitions_controller.rb
class MmaDefinitionsController < ApplicationController
  before_action :set_mma_definition, only: [:show, :edit, :update, :destroy]

  # GET /mma_definitions
  # GET /mma_definitions.json
  def index
    @mma_definitions = MmaDefinition.all
  end

  # GET /mma_definitions/1
  # GET /mma_definitions/1.json
  def show
  end

  # GET /mma_definitions/new
  def new
    @mma_definition = MmaDefinition.new
  end

  # GET /mma_definitions/1/edit
  def edit
  end

  # POST /mma_definitions
  # POST /mma_definitions.json
  def create
    @mma_definition = MmaDefinition.new(mma_definition_params)

    respond_to do |format|
      if @mma_definition.save
        format.html { redirect_to @mma_definition, notice: 'Mma definition was successfully created.' }
        format.json { render :show, status: :created, location: @mma_definition }
      else
        format.html { render :new }
        format.json { render json: @mma_definition.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /mma_definitions/1
  # PATCH/PUT /mma_definitions/1.json
  def update
    respond_to do |format|
      if @mma_definition.update(mma_definition_params)
        format.html { redirect_to @mma_definition, notice: 'Mma definition was successfully updated.' }
        format.json { render :show, status: :ok, location: @mma_definition }
      else
        format.html { render :edit }
        format.json { render json: @mma_definition.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /mma_definitions/1
  # DELETE /mma_definitions/1.json
  def destroy
    @mma_definition.destroy
    respond_to do |format|
      format.html { redirect_to mma_definitions_url, notice: 'Mma definition was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_mma_definition
      @mma_definition = MmaDefinition.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def mma_definition_params
      params.require(:mma_definition).permit(:name)
    end
end

app/controllers/workout_classes_controller.rb
class WorkoutClassesController < ApplicationController
  before_action :set_workout_class, only: [:show, :edit, :update, :destroy]

  # GET /workout_classes
  # GET /workout_classes.json
  def index
    @workout_classes = WorkoutClass.all
  end

  # GET /workout_classes/1
  # GET /workout_classes/1.json
  def show
  end

  # GET /workout_classes/new
  def new
    @workout_class = WorkoutClass.new
  end

  # GET /workout_classes/1/edit
  def edit
  end

  # POST /workout_classes
  # POST /workout_classes.json
  def create
    @workout_class = WorkoutClass.new(workout_class_params)

    respond_to do |format|
      if @workout_class.save
        format.html { redirect_to @workout_class, notice: 'Workout class was successfully created.' }
        format.json { render :show, status: :created, location: @workout_class }
      else
        format.html { render :new }
        format.json { render json: @workout_class.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /workout_classes/1
  # PATCH/PUT /workout_classes/1.json
  def update
    respond_to do |format|
      if @workout_class.update(workout_class_params)
        format.html { redirect_to @workout_class, notice: 'Workout class was successfully updated.' }
        format.json { render :show, status: :ok, location: @workout_class }
      else
        format.html { render :edit }
        format.json { render json: @workout_class.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /workout_classes/1
  # DELETE /workout_classes/1.json
  def destroy
    @workout_class.destroy
    respond_to do |format|
      format.html { redirect_to workout_classes_url, notice: 'Workout class was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_workout_class
      @workout_class = WorkoutClass.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def workout_class_params
      params.require(:workout_class).permit(:details, :workout_definition_id, :time, :day)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/calendar_helper.rb
module CalendarHelper
end

app/helpers/cardio_definitions_helper.rb
module CardioDefinitionsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/mma_definitions_helper.rb
module MmaDefinitionsHelper
end

app/helpers/weightlifting_definitions_helper.rb
module WeightliftingDefinitionsHelper
end

app/helpers/workout_classes_helper.rb
module WorkoutClassesHelper
end

app/helpers/workout_definitions_helper.rb
module WorkoutDefinitionsHelper


	def days_since workout_def
		most_recent = workout_def.workout_transactions.maximum(:date)
		if (most_recent.nil?)
			''
		else
			(DateTime.now.to_date - most_recent).to_i
		end
	end
end

app/helpers/workout_transactions_helper.rb
module WorkoutTransactionsHelper
end

app/views/home/index.html.erb
<div class="workout-defs">
	<% @workout_defs.each do |type, defs| %>
		<div class="workout-def">
			<h1><%= type.gsub('Definition','') %></h1>
			<ul>
				<% defs.each do |d| %>
					<li>
						<div class="def-name"><%= d.name %> (days since: <%= days_since(d) %>)</div>
						<div class="add-link">
							<%= link_to 'Add', new_workout_transaction_path(:workout_def => d) %>
						</div>
					</li>
				<% end %>
			</ul>
		</div>
	<% end %>
</div>

app/views/workout_classes/_form.html.erb
<%= form_for(@workout_class) do |f| %>
  <% if @workout_class.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@workout_class.errors.count, "error") %> prohibited this workout_class from being saved:</h2>

      <ul>
      <% @workout_class.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :details %><br>
    <%= f.text_field :details %>
  </div>
  <div class="field">
    <%= f.label :workout_definition_id %><br>
    <%= f.text_field :workout_definition_id %>
  </div>
  <div class="field">
    <%= f.label :time %><br>
    <%= f.text_field :time %>
  </div>
  <div class="field">
    <%= f.label :day %><br>
    <%= f.number_field :day %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/workout_classes/edit.html.erb
<h1>Editing Workout Class</h1>

<%= render 'form' %>

<%= link_to 'Show', @workout_class %> |
<%= link_to 'Back', workout_classes_path %>

app/views/workout_classes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Workout Classes</h1>

<table>
  <thead>
    <tr>
      <th>Details</th>
      <th>Workout definition</th>
      <th>Time</th>
      <th>Day</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @workout_classes.each do |workout_class| %>
      <tr>
        <td><%= workout_class.details %></td>
        <td><%= workout_class.workout_definition %></td>
        <td><%= workout_class.time %></td>
        <td><%= workout_class.day %></td>
        <td><%= link_to 'Show', workout_class %></td>
        <td><%= link_to 'Edit', edit_workout_class_path(workout_class) %></td>
        <td><%= link_to 'Destroy', workout_class, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Workout class', new_workout_class_path %>

app/views/workout_classes/new.html.erb
<h1>New Workout Class</h1>

<%= render 'form' %>

<%= link_to 'Back', workout_classes_path %>

app/views/workout_classes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Details:</strong>
  <%= @workout_class.details %>
</p>

<p>
  <strong>Workout definition:</strong>
  <%= @workout_class.workout_definition %>
</p>

<p>
  <strong>Time:</strong>
  <%= @workout_class.time %>
</p>

<p>
  <strong>Day:</strong>
  <%= @workout_class.day %>
</p>

<%= link_to 'Edit', edit_workout_class_path(@workout_class) %> |
<%= link_to 'Back', workout_classes_path %>