config/routes.rb
Rails.application.routes.draw do

  resources :workout_classes
  root 'home#index'

  get '/calendar', to: 'calendar#index'
  get '/load', to: 'workout_transactions#load'
  post '/parse', to: 'workout_transactions#parse'
  
  resources :workout_transactions
  resources :cardio_definitions
  resources :mma_definitions
  resources :weightlifting_definitions
  resources :workout_definitions

end

app/controllers/workout_transactions_controller.rb
class WorkoutTransactionsController < ApplicationController
  before_action :set_workout_transaction, only: [:show, :edit, :update, :destroy]

  # GET /workout_transactions
  # GET /workout_transactions.json
  def index
    @workout_transactions = WorkoutTransaction.all
  end

  # GET /workout_transactions/1
  # GET /workout_transactions/1.json
  def show
  end

  # GET /workout_transactions/new
  def new
    @workout_transaction = WorkoutTransaction.new
    unless params[:workout_def].nil?
      @workout_def = WorkoutDefinition.find(params[:workout_def])
      @workout_transaction.workout_definitions.push(@workout_def)
    end
  end

  # GET /workout_transactions/1/edit
  def edit
  end

  def load

  end

  def parse
    input = params[:input]
    # Split by newline characters and reject any line that does not start with a number (date)
    # This will give us an array of strings like
    # 8/16: abs, back
    workouts = input.split(/(\r\n)|(\n)/).reject{|l|l.match /^\D/}
    if workouts.count > 0
      # Grab all different muscle groups by getting the names of all the weight lifting defs
      mgs = WorkoutDefinition.all.map{|w|w.name}
      # Delete all other imported transactions
      to_delete = WorkoutTransaction.where(is_imported: true)
      to_delete.delete_all
      workouts.each do |w|
        txn = WorkoutTransaction.new
        txn.is_imported = true
        date_regex = /([\d]+\/[\d]+):.*/
        # If we match the pattern like "8/16: otherstuff", then grab the 8/16 part and set it as the date
        if w.match(date_regex)
          date_string = w.gsub(date_regex,'\1')
          date_string = w.gsub(date_regex,'\1')
          txn.date = Date.strptime(date_string,'%m/%d')
        end
        txn.save!
        # Grab the different areas (e.g. 'back, abs')
        areas = w.gsub(/[\d]+\/[\d]+:[\s]*/,'').split(/,[\s]*/)
        rejected_areas = areas.clone
        areas.reject!{|a| !(mgs.include?(a))}
        rejected_areas.reject!{|a| mgs.include?(a)}
        unless rejected_areas.empty?
          txn.details = "(#{rejected_areas.join(', ')})"
        end
        # Initialize workout maps if nil
        areas.each do |a|
          wdef = WorkoutDefinition.where(name: a).first
          txn.workout_maps.create(workout_transaction: txn, workout_definition: wdef)
        end
        txn.save!
      end
    end
    redirect_to '/calendar'
  end

  # POST /workout_transactions
  # POST /workout_transactions.json
  def create
    @workout_transaction = WorkoutTransaction.new(workout_transaction_params)
    txn = params['workout_transaction']

    # Will look something like ['','1','2','3'] for defs 1, 2, and 3
    defs = txn['workout_definitions']
    # We need to remove the ''
    defs.reject!{|w| w == ''}
    # Then set our txn's defs.
    @workout_transaction.workout_definitions = WorkoutDefinition.find(defs)

    # Our time is also set in a format like {1=>year,2=>month,3=>day,4=>hour,5=>minute}
    # We just want the hour/minute
    @workout_transaction.time = "#{txn['time(4i)']}:#{txn['time(5i)']}"

    respond_to do |format|
      if @workout_transaction.save
        format.html { redirect_to @workout_transaction, notice: 'Workout transaction was successfully created.' }
        format.json { render :show, status: :created, location: @workout_transaction }
      else
        format.html { render :new }
        format.json { render json: @workout_transaction.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /workout_transactions/1
  # PATCH/PUT /workout_transactions/1.json
  def update
    respond_to do |format|
      if @workout_transaction.update(workout_transaction_params)
        format.html { redirect_to @workout_transaction, notice: 'Workout transaction was successfully updated.' }
        format.json { render :show, status: :ok, location: @workout_transaction }
      else
        format.html { render :edit }
        format.json { render json: @workout_transaction.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /workout_transactions/1
  # DELETE /workout_transactions/1.json
  def destroy
    @workout_transaction.destroy
    respond_to do |format|
      format.html { redirect_to workout_transactions_url, notice: 'Workout transaction was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_workout_transaction
      @workout_transaction = WorkoutTransaction.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def workout_transaction_params
      params.require(:workout_transaction).permit(:details, :date, :time, :workout_definitions)
    end
end

app/helpers/workout_transactions_helper.rb
module WorkoutTransactionsHelper
end

app/views/workout_transactions/_form.html.erb
<%= form_for(@workout_transaction) do |f| %>
  <% if @workout_transaction.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@workout_transaction.errors.count, "error") %> prohibited this workout_transaction from being saved:</h2>

      <ul>
      <% @workout_transaction.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :details %><br>
    <%= f.text_field :details %>
  </div>
  <div class="field">
    <%= f.label :date %><br>
    <%= f.date_select :date, {:default => DateTime.now.to_date}%>
  </div>
  <div class="field">
    <%= f.label :time %><br>
    <%= f.time_select :time %>
  </div>
  <div class="field">
    <%= f.label :workout_definitions %><br>
    <%= f.select :workout_definitions, options_for_select(WorkoutDefinition.all.collect{|w| [w.name, w.id]}, selected: ((@workout_def.nil?)?(0):(@workout_def.id))), {:prompt => ''}, {:multiple => true} %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/workout_transactions/edit.html.erb
<h1>Editing Workout Transaction</h1>

<%= render 'form' %>

<%= link_to 'Show', @workout_transaction %> |
<%= link_to 'Back', workout_transactions_path %>

app/views/workout_transactions/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Workout Transactions</h1>

<table>
  <thead>
    <tr>
      <th>Details</th>
      <th>Date</th>
      <th>Time</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @workout_transactions.each do |workout_transaction| %>
      <tr>
        <td><%= workout_transaction.details %></td>
        <td><%= workout_transaction.date %></td>
        <td><%= workout_transaction.time %></td>
        <td><%= link_to 'Show', workout_transaction %></td>
        <td><%= link_to 'Edit', edit_workout_transaction_path(workout_transaction) %></td>
        <td><%= link_to 'Destroy', workout_transaction, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Workout transaction', new_workout_transaction_path %>

app/views/workout_transactions/load.html.erb
<%= csrf_meta_tags %>
<%= form_tag '/parse' do %>
	<%= text_area_tag :input %>
	<%= submit_tag 'Submit' %>
<% end %>

app/views/workout_transactions/new.html.erb
<h1>New Workout Transaction</h1>

<%= render 'form' %>

<%= link_to 'Back', workout_transactions_path %>

app/views/workout_transactions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Details:</strong>
  <%= @workout_transaction.details %>
</p>

<p>
  <strong>Date:</strong>
  <%= @workout_transaction.date %>
</p>

<p>
  <strong>Time:</strong>
  <%= @workout_transaction.time %>
</p>

<%= link_to 'Edit', edit_workout_transaction_path(@workout_transaction) %> |
<%= link_to 'Back', workout_transactions_path %>