config/routes.rb
Rails.application.routes.draw do

  resources :workout_classes
  root 'home#index'

  get '/calendar', to: 'calendar#index'
  get '/load', to: 'workout_transactions#load'
  post '/parse', to: 'workout_transactions#parse'
  
  resources :workout_transactions
  resources :cardio_definitions
  resources :mma_definitions
  resources :weightlifting_definitions
  resources :workout_definitions

end

app/models/workout_definition.rb
class WorkoutDefinition < ActiveRecord::Base
	has_many :workout_maps
	has_many :workout_transactions, through: :workout_maps
	attr_accessor :most_recent
end

app/controllers/workout_definitions_controller.rb
class WorkoutDefinitionsController < ApplicationController
  before_action :set_workout_definition, only: [:show, :edit, :update, :destroy]

  # GET /workout_definitions
  # GET /workout_definitions.json
  def index
    @workout_definitions = WorkoutDefinition.all
  end

  # GET /workout_definitions/1
  # GET /workout_definitions/1.json
  def show
  end

  # GET /workout_definitions/new
  def new
    @workout_definition = WorkoutDefinition.new
  end

  # GET /workout_definitions/1/edit
  def edit
  end

  # POST /workout_definitions
  # POST /workout_definitions.json
  def create
    @workout_definition = WorkoutDefinition.new(workout_definition_params)

    respond_to do |format|
      if @workout_definition.save
        format.html { redirect_to @workout_definition, notice: 'Workout definition was successfully created.' }
        format.json { render :show, status: :created, location: @workout_definition }
      else
        format.html { render :new }
        format.json { render json: @workout_definition.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /workout_definitions/1
  # PATCH/PUT /workout_definitions/1.json
  def update
    respond_to do |format|
      if @workout_definition.update(workout_definition_params)
        format.html { redirect_to @workout_definition, notice: 'Workout definition was successfully updated.' }
        format.json { render :show, status: :ok, location: @workout_definition }
      else
        format.html { render :edit }
        format.json { render json: @workout_definition.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /workout_definitions/1
  # DELETE /workout_definitions/1.json
  def destroy
    @workout_definition.destroy
    respond_to do |format|
      format.html { redirect_to workout_definitions_url, notice: 'Workout definition was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_workout_definition
      @workout_definition = WorkoutDefinition.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def workout_definition_params
      params.require(:workout_definition).permit(:name, :type)
    end
end

app/helpers/workout_definitions_helper.rb
module WorkoutDefinitionsHelper


	def days_since workout_def
		most_recent = workout_def.workout_transactions.maximum(:date)
		if (most_recent.nil?)
			''
		else
			(DateTime.now.to_date - most_recent).to_i
		end
	end
end

app/views/workout_definitions/_form.html.erb
<%= form_for(@workout_definition) do |f| %>
  <% if @workout_definition.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@workout_definition.errors.count, "error") %> prohibited this workout_definition from being saved:</h2>

      <ul>
      <% @workout_definition.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :type %><br>
    <%= f.text_field :type %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/workout_definitions/edit.html.erb
<h1>Editing Workout Definition</h1>

<%= render 'form' %>

<%= link_to 'Show', @workout_definition %> |
<%= link_to 'Back', workout_definitions_path %>

app/views/workout_definitions/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Workout Definitions</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Type</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @workout_definitions.each do |workout_definition| %>
      <tr>
        <td><%= workout_definition.name %></td>
        <td><%= workout_definition.type %></td>
        <td><%= link_to 'Show', workout_definition %></td>
        <td><%= link_to 'Edit', edit_workout_definition_path(workout_definition) %></td>
        <td><%= link_to 'Destroy', workout_definition, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Workout definition', new_workout_definition_path %>

app/views/workout_definitions/new.html.erb
<h1>New Workout Definition</h1>

<%= render 'form' %>

<%= link_to 'Back', workout_definitions_path %>

app/views/workout_definitions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @workout_definition.name %>
</p>

<p>
  <strong>Type:</strong>
  <%= @workout_definition.type %>
</p>

<%= link_to 'Edit', edit_workout_definition_path(@workout_definition) %> |
<%= link_to 'Back', workout_definitions_path %>