config/routes.rb
Rails.application.routes.draw do

  resources :workout_classes
  root 'home#index'

  get '/calendar', to: 'calendar#index'
  get '/load', to: 'workout_transactions#load'
  post '/parse', to: 'workout_transactions#parse'
  
  resources :workout_transactions
  resources :cardio_definitions
  resources :mma_definitions
  resources :weightlifting_definitions
  resources :workout_definitions

end

app/models/mma_definition.rb
class MmaDefinition < WorkoutDefinition
end

app/controllers/mma_definitions_controller.rb
class MmaDefinitionsController < ApplicationController
  before_action :set_mma_definition, only: [:show, :edit, :update, :destroy]

  # GET /mma_definitions
  # GET /mma_definitions.json
  def index
    @mma_definitions = MmaDefinition.all
  end

  # GET /mma_definitions/1
  # GET /mma_definitions/1.json
  def show
  end

  # GET /mma_definitions/new
  def new
    @mma_definition = MmaDefinition.new
  end

  # GET /mma_definitions/1/edit
  def edit
  end

  # POST /mma_definitions
  # POST /mma_definitions.json
  def create
    @mma_definition = MmaDefinition.new(mma_definition_params)

    respond_to do |format|
      if @mma_definition.save
        format.html { redirect_to @mma_definition, notice: 'Mma definition was successfully created.' }
        format.json { render :show, status: :created, location: @mma_definition }
      else
        format.html { render :new }
        format.json { render json: @mma_definition.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /mma_definitions/1
  # PATCH/PUT /mma_definitions/1.json
  def update
    respond_to do |format|
      if @mma_definition.update(mma_definition_params)
        format.html { redirect_to @mma_definition, notice: 'Mma definition was successfully updated.' }
        format.json { render :show, status: :ok, location: @mma_definition }
      else
        format.html { render :edit }
        format.json { render json: @mma_definition.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /mma_definitions/1
  # DELETE /mma_definitions/1.json
  def destroy
    @mma_definition.destroy
    respond_to do |format|
      format.html { redirect_to mma_definitions_url, notice: 'Mma definition was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_mma_definition
      @mma_definition = MmaDefinition.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def mma_definition_params
      params.require(:mma_definition).permit(:name)
    end
end

app/helpers/mma_definitions_helper.rb
module MmaDefinitionsHelper
end

app/views/mma_definitions/_form.html.erb
<%= form_for(@mma_definition) do |f| %>
  <% if @mma_definition.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@mma_definition.errors.count, "error") %> prohibited this mma_definition from being saved:</h2>

      <ul>
      <% @mma_definition.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/mma_definitions/edit.html.erb
<h1>Editing Mma Definition</h1>

<%= render 'form' %>

<%= link_to 'Show', @mma_definition %> |
<%= link_to 'Back', mma_definitions_path %>

app/views/mma_definitions/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Mma Definitions</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @mma_definitions.each do |mma_definition| %>
      <tr>
        <td><%= mma_definition.name %></td>
        <td><%= link_to 'Show', mma_definition %></td>
        <td><%= link_to 'Edit', edit_mma_definition_path(mma_definition) %></td>
        <td><%= link_to 'Destroy', mma_definition, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Mma definition', new_mma_definition_path %>

app/views/mma_definitions/new.html.erb
<h1>New Mma Definition</h1>

<%= render 'form' %>

<%= link_to 'Back', mma_definitions_path %>

app/views/mma_definitions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @mma_definition.name %>
</p>

<%= link_to 'Edit', edit_mma_definition_path(@mma_definition) %> |
<%= link_to 'Back', mma_definitions_path %>